============================= test session starts ==============================
platform linux -- Python 3.10.16, pytest-8.3.5, pluggy-1.6.0
rootdir: /home/jn_cndt4/project/code repair/BugAgent/BugAgent_1.3/data/QuixBugs_test
plugins: anyio-4.9.0, timeout-2.4.0
timeout: 5.0s
timeout method: signal
timeout func_only: False
collected 5 items

python_testcases/test_breadth_first_search.py ..F..                      [100%]

=================================== FAILURES ===================================
____________________________________ test3 _____________________________________

    def test3():
        """Case 3: Two unconnected nodes in graph
        Output: Path not found
        """
    
        nodef = Node("F")
        nodee = Node("E")
    
>       path_found = breadth_first_search(nodef, nodee)

python_testcases/test_breadth_first_search.py:52: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

startnode = <node.Node object at 0x7f4ebc9bfee0>
goalnode = <node.Node object at 0x7f4ebc9bd840>

    def breadth_first_search(startnode, goalnode):
        queue = Queue()
        queue.append(startnode)
    
        nodesseen = set()
        nodesseen.add(startnode)
    
        while True:
>           node = queue.popleft()
E           IndexError: pop from an empty deque

python_programs/breadth_first_search.py:12: IndexError
=========================== short test summary info ============================
FAILED python_testcases/test_breadth_first_search.py::test3 - IndexError: pop...
========================= 1 failed, 4 passed in 0.03s ==========================
