============================= test session starts ==============================
platform linux -- Python 3.10.16, pytest-8.3.5, pluggy-1.6.0
rootdir: /home/jn_cndt4/project/code repair/BugAgent/BugAgent_1.3/data/QuixBugs_test
plugins: anyio-4.9.0, timeout-2.4.0
timeout: 5.0s
timeout method: signal
timeout func_only: False
collected 6 items

python_testcases/test_gcd.py .FFFFF                                      [100%]

=================================== FAILURES ===================================
___________________________ test_gcd[input_data1-13] ___________________________

input_data = [13, 13], expected = 13

    @pytest.mark.parametrize("input_data,expected", testdata)
    def test_gcd(input_data, expected):
>       assert gcd(*input_data) == expected

python_testcases/test_gcd.py:15: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
python_programs/gcd.py:5: in gcd
    return gcd(a % b, b)
python_programs/gcd.py:5: in gcd
    return gcd(a % b, b)
python_programs/gcd.py:5: in gcd
    return gcd(a % b, b)
E   RecursionError: maximum recursion depth exceeded in comparison
!!! Recursion detected (same locals & position)
___________________________ test_gcd[input_data2-1] ____________________________

input_data = [37, 600], expected = 1

    @pytest.mark.parametrize("input_data,expected", testdata)
    def test_gcd(input_data, expected):
>       assert gcd(*input_data) == expected

python_testcases/test_gcd.py:15: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
python_programs/gcd.py:5: in gcd
    return gcd(a % b, b)
python_programs/gcd.py:5: in gcd
    return gcd(a % b, b)
E   RecursionError: maximum recursion depth exceeded in comparison
!!! Recursion detected (same locals & position)
___________________________ test_gcd[input_data3-20] ___________________________

input_data = [20, 100], expected = 20

    @pytest.mark.parametrize("input_data,expected", testdata)
    def test_gcd(input_data, expected):
>       assert gcd(*input_data) == expected

python_testcases/test_gcd.py:15: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
python_programs/gcd.py:5: in gcd
    return gcd(a % b, b)
python_programs/gcd.py:5: in gcd
    return gcd(a % b, b)
E   RecursionError: maximum recursion depth exceeded in comparison
!!! Recursion detected (same locals & position)
_________________________ test_gcd[input_data4-18913] __________________________

input_data = [624129, 2061517], expected = 18913

    @pytest.mark.parametrize("input_data,expected", testdata)
    def test_gcd(input_data, expected):
>       assert gcd(*input_data) == expected

python_testcases/test_gcd.py:15: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
python_programs/gcd.py:5: in gcd
    return gcd(a % b, b)
python_programs/gcd.py:5: in gcd
    return gcd(a % b, b)
E   RecursionError: maximum recursion depth exceeded in comparison
!!! Recursion detected (same locals & position)
___________________________ test_gcd[input_data5-3] ____________________________

input_data = [3, 12], expected = 3

    @pytest.mark.parametrize("input_data,expected", testdata)
    def test_gcd(input_data, expected):
>       assert gcd(*input_data) == expected

python_testcases/test_gcd.py:15: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
python_programs/gcd.py:5: in gcd
    return gcd(a % b, b)
python_programs/gcd.py:5: in gcd
    return gcd(a % b, b)
E   RecursionError: maximum recursion depth exceeded in comparison
!!! Recursion detected (same locals & position)
=========================== short test summary info ============================
FAILED python_testcases/test_gcd.py::test_gcd[input_data1-13] - RecursionErro...
FAILED python_testcases/test_gcd.py::test_gcd[input_data2-1] - RecursionError...
FAILED python_testcases/test_gcd.py::test_gcd[input_data3-20] - RecursionErro...
FAILED python_testcases/test_gcd.py::test_gcd[input_data4-18913] - RecursionE...
FAILED python_testcases/test_gcd.py::test_gcd[input_data5-3] - RecursionError...
========================= 5 failed, 1 passed in 0.05s ==========================
