============================= test session starts ==============================
platform linux -- Python 3.10.16, pytest-8.3.5, pluggy-1.6.0
rootdir: /home/jn_cndt4/project/code repair/BugAgent/BugAgent_1.3/data/QuixBugs_test
plugins: anyio-4.9.0, timeout-2.4.0
timeout: 5.0s
timeout method: signal
timeout func_only: False
collected 12 items

python_testcases/test_lis.py ........FFFF                                [100%]

=================================== FAILURES ===================================
___________________________ test_lis[input_data8-3] ____________________________

input_data = [[4, 1, 5, 3, 7, 6, ...]], expected = 3

    @pytest.mark.parametrize("input_data,expected", testdata)
    def test_lis(input_data, expected):
>       assert lis(*input_data) == expected
E       assert 2 == 3
E        +  where 2 = lis(*[[4, 1, 5, 3, 7, 6, ...]])

python_testcases/test_lis.py:15: AssertionError
___________________________ test_lis[input_data9-6] ____________________________

input_data = [[10, 22, 9, 33, 21, 50, ...]], expected = 6

    @pytest.mark.parametrize("input_data,expected", testdata)
    def test_lis(input_data, expected):
>       assert lis(*input_data) == expected
E       assert 5 == 6
E        +  where 5 = lis(*[[10, 22, 9, 33, 21, 50, ...]])

python_testcases/test_lis.py:15: AssertionError
___________________________ test_lis[input_data10-3] ___________________________

input_data = [[7, 10, 9, 2, 3, 8, ...]], expected = 3

    @pytest.mark.parametrize("input_data,expected", testdata)
    def test_lis(input_data, expected):
>       assert lis(*input_data) == expected
E       assert 1 == 3
E        +  where 1 = lis(*[[7, 10, 9, 2, 3, 8, ...]])

python_testcases/test_lis.py:15: AssertionError
___________________________ test_lis[input_data11-4] ___________________________

input_data = [[9, 11, 2, 13, 7, 15]], expected = 4

    @pytest.mark.parametrize("input_data,expected", testdata)
    def test_lis(input_data, expected):
>       assert lis(*input_data) == expected
E       assert 3 == 4
E        +  where 3 = lis(*[[9, 11, 2, 13, 7, 15]])

python_testcases/test_lis.py:15: AssertionError
=========================== short test summary info ============================
FAILED python_testcases/test_lis.py::test_lis[input_data8-3] - assert 2 == 3
FAILED python_testcases/test_lis.py::test_lis[input_data9-6] - assert 5 == 6
FAILED python_testcases/test_lis.py::test_lis[input_data10-3] - assert 1 == 3
FAILED python_testcases/test_lis.py::test_lis[input_data11-4] - assert 3 == 4
========================= 4 failed, 8 passed in 0.04s ==========================
