============================= test session starts ==============================
platform linux -- Python 3.10.16, pytest-8.3.5, pluggy-1.6.0
rootdir: /home/jn_cndt4/project/code repair/BugAgent/BugAgent_1.3/data/QuixBugs_test
plugins: anyio-4.9.0, timeout-2.4.0
timeout: 5.0s
timeout method: signal
timeout func_only: False
collected 8 items

python_testcases/test_next_permutation.py FFFFFFFF                       [100%]

=================================== FAILURES ===================================
_________________ test_next_permutation[input_data0-expected0] _________________

input_data = [[3, 2, 4, 1]], expected = [3, 4, 1, 2]

    @pytest.mark.parametrize("input_data,expected", testdata)
    def test_next_permutation(input_data, expected):
>       assert next_permutation(*input_data) == expected
E       assert [3, 1, 2, 4] == [3, 4, 1, 2]
E         
E         At index 1 diff: 1 != 4
E         Use -v to get more diff

python_testcases/test_next_permutation.py:15: AssertionError
_________________ test_next_permutation[input_data1-expected1] _________________

input_data = [[3, 5, 6, 2, 1]], expected = [3, 6, 1, 2, 5]

    @pytest.mark.parametrize("input_data,expected", testdata)
    def test_next_permutation(input_data, expected):
>       assert next_permutation(*input_data) == expected
E       assert [3, 1, 5, 2, 6] == [3, 6, 1, 2, 5]
E         
E         At index 1 diff: 1 != 6
E         Use -v to get more diff

python_testcases/test_next_permutation.py:15: AssertionError
_________________ test_next_permutation[input_data2-expected2] _________________

input_data = [[3, 5, 6, 2]], expected = [3, 6, 2, 5]

    @pytest.mark.parametrize("input_data,expected", testdata)
    def test_next_permutation(input_data, expected):
>       assert next_permutation(*input_data) == expected
E       assert [3, 2, 5, 6] == [3, 6, 2, 5]
E         
E         At index 1 diff: 2 != 6
E         Use -v to get more diff

python_testcases/test_next_permutation.py:15: AssertionError
_________________ test_next_permutation[input_data3-expected3] _________________

input_data = [[4, 5, 1, 7, 9]], expected = [4, 5, 1, 9, 7]

    @pytest.mark.parametrize("input_data,expected", testdata)
    def test_next_permutation(input_data, expected):
>       assert next_permutation(*input_data) == expected
E       assert [1, 9, 7, 4, 5] == [4, 5, 1, 9, 7]
E         
E         At index 0 diff: 1 != 4
E         Use -v to get more diff

python_testcases/test_next_permutation.py:15: AssertionError
_________________ test_next_permutation[input_data4-expected4] _________________

input_data = [[4, 5, 8, 7, 1]], expected = [4, 7, 1, 5, 8]

    @pytest.mark.parametrize("input_data,expected", testdata)
    def test_next_permutation(input_data, expected):
>       assert next_permutation(*input_data) == expected
E       assert [4, 1, 5, 7, 8] == [4, 7, 1, 5, 8]
E         
E         At index 1 diff: 1 != 7
E         Use -v to get more diff

python_testcases/test_next_permutation.py:15: AssertionError
_________________ test_next_permutation[input_data5-expected5] _________________

input_data = [[9, 5, 2, 6, 1]], expected = [9, 5, 6, 1, 2]

    @pytest.mark.parametrize("input_data,expected", testdata)
    def test_next_permutation(input_data, expected):
>       assert next_permutation(*input_data) == expected
E       assert [9, 5, 1, 2, 6] == [9, 5, 6, 1, 2]
E         
E         At index 2 diff: 1 != 6
E         Use -v to get more diff

python_testcases/test_next_permutation.py:15: AssertionError
_________________ test_next_permutation[input_data6-expected6] _________________

input_data = [[44, 5, 1, 7, 9]], expected = [44, 5, 1, 9, 7]

    @pytest.mark.parametrize("input_data,expected", testdata)
    def test_next_permutation(input_data, expected):
>       assert next_permutation(*input_data) == expected
E       assert None == [44, 5, 1, 9, 7]
E        +  where None = next_permutation(*[[44, 5, 1, 7, 9]])

python_testcases/test_next_permutation.py:15: AssertionError
_________________ test_next_permutation[input_data7-expected7] _________________

input_data = [[3, 4, 5]], expected = [3, 5, 4]

    @pytest.mark.parametrize("input_data,expected", testdata)
    def test_next_permutation(input_data, expected):
>       assert next_permutation(*input_data) == expected
E       assert None == [3, 5, 4]
E        +  where None = next_permutation(*[[3, 4, 5]])

python_testcases/test_next_permutation.py:15: AssertionError
=========================== short test summary info ============================
FAILED python_testcases/test_next_permutation.py::test_next_permutation[input_data0-expected0]
FAILED python_testcases/test_next_permutation.py::test_next_permutation[input_data1-expected1]
FAILED python_testcases/test_next_permutation.py::test_next_permutation[input_data2-expected2]
FAILED python_testcases/test_next_permutation.py::test_next_permutation[input_data3-expected3]
FAILED python_testcases/test_next_permutation.py::test_next_permutation[input_data4-expected4]
FAILED python_testcases/test_next_permutation.py::test_next_permutation[input_data5-expected5]
FAILED python_testcases/test_next_permutation.py::test_next_permutation[input_data6-expected6]
FAILED python_testcases/test_next_permutation.py::test_next_permutation[input_data7-expected7]
============================== 8 failed in 0.04s ===============================
