============================= test session starts ==============================
platform linux -- Python 3.10.16, pytest-8.3.5, pluggy-1.6.0
rootdir: /home/jn_cndt4/project/code repair/BugAgent/BugAgent_1.3/data/QuixBugs_test
plugins: anyio-4.9.0, timeout-2.4.0
timeout: 5.0s
timeout method: signal
timeout func_only: False
collected 4 items

python_testcases/test_shortest_path_length.py FF..                       [100%]

=================================== FAILURES ===================================
____________________________________ test1 _____________________________________

    def test1():
        """Case 1: One path
        Output: 4
        """
    
        result = shortest_path_length(length_by_edge, node0, node1)
>       assert result == 4
E       assert 1 == 4

python_testcases/test_shortest_path_length.py:34: AssertionError
____________________________________ test2 _____________________________________

    def test2():
        """Case 2: Multiple path
        Output: 7
        """
    
        result = shortest_path_length(length_by_edge, node0, node5)
>       assert result == 7
E       assert 10 == 7

python_testcases/test_shortest_path_length.py:43: AssertionError
=========================== short test summary info ============================
FAILED python_testcases/test_shortest_path_length.py::test1 - assert 1 == 4
FAILED python_testcases/test_shortest_path_length.py::test2 - assert 10 == 7
========================= 2 failed, 2 passed in 0.03s ==========================
